# A pollution sensor based upon the amazing 
# https://www.ikea.com/gb/en/p/vindriktning-air-quality-sensor-80515910/

esphome:
  name: vindrikting-kitchen
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
# ESPHome now uses the Noise Protocol Framework to secure the API comms
# Create individual entry for each device using a 32-character base64 pre-shared key
# name: key

api:
  encryption:
    key: !secret device_api_encryption_key

ota:
  password: "i like beans"

#I've found ESPHome works better with a static IP 
wifi:
  manual_ip:
    static_ip: 192.168.0.0
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ssid: "add yours here"
  password: "i still like beans"


captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600
  
sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s  
  
- platform: pm1006
  pm_2_5:
    name: "PM2.5 sensor in lounge"
    accuracy_decimals: 2
    filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 10
          send_first_at: 10
- platform: template
  name: "PM2.5 sensor in lounge - Power Usage"
  id: power_consumption
  device_class: power
  state_class: measurement
  unit_of_measurement: W
  accuracy_decimals: 4
  filters:
    - heartbeat: 60s
- platform: integration
  name: "PM2.5 sensor in lounge - Consumed Energy"
  sensor: power_consumption
  time_unit: 'h'
  device_class: energy
  state_class: total_increasing
  unit_of_measurement: 'Wh'
  restore: false
  integration_method: left

interval:
- interval: 1min
  then:
    - sensor.template.publish:
        id: power_consumption
        state: 0.5696
