esphome:
  name: cactus-water
  platform: ESP8266
  board: d1_mini

  # Enable logging
  logger:

  # Enable Home Assistant API
  api:

  ota:
    password: "i like beans"

  #I've found ESPHome works better with a static IP
  wifi:
    manual_ip:
      static_ip: 192.168.0.0
      gateway: 192.168.0.1
      subnet: 255.255.255.0
    ssid: "add yours here"
    password: "i still like beans"


  captive_portal:


# Dry (in air) is 0.71V
# In a wet env, it is 0.47V
# fully submerged, it is 0.3V
# 8266 ADC has range of 0-1V, so this is problematic


  - platform: adc
    pin: A0
    id: moisture1
    name: "Cactus Soil Moisture Level"
    unit_of_measurement: "%"
    accuracy_decimals: 2
    state_class: measurement
    icon: "mdi:water-percent"
    update_interval: 60s
    filters:
      - calibrate_linear:
          # Map the voltage reading when fully submerged in water to 100% moisture
          - 0.27441 -> 100.0
          # Map the voltage reading when completely dry to 0% moisture
          - 0.67578 -> 0.0