esphome:
  name: cactus-water
  platform: ESP8266
  board: d1_mini

  # Enable logging
  logger:

  # Enable Home Assistant API
  api:

  ota:
    password: "i like beans"

  #I've found ESPHome works better with a static IP
  wifi:
    manual_ip:
      static_ip: 192.168.0.0
      gateway: 192.168.0.1
      subnet: 255.255.255.0
    ssid: "add yours here"
    password: "i still like beans"


  captive_portal:


# Dry (in air) is 0.71V
# In a wet env, it is 0.47V
# fully submerged, it is 0.3V
# 8266 ADC has range of 0-1V, so this is problematic


sensor:
  - platform: adc
    pin: A0
    name: "Soil Moisture Level"
    update_interval: 60s
    unit_of_measurement: "%"
    filters:
    - median: # smooth out the data being received as it could be noisy 
         window_size: 7 # take 7 readings 
         send_every: 4 # eport the median value of the last 7 readings every 4th reading.
         send_first_at: 1
    - calibrate_linear:
        - 0.71 -> 0.00 # dry as hell
        - 0.47 -> 100.00 # wet as hell 
    # # the esp8266 only operates between 0v and 1v, so you need to adapt this. also only report on up to 100%    
    - lambda: |
        if (x < 0) return 0; 
        else if (x > 100) return 100; 
        else return (x);
    accuracy_decimals: 0